stocks_dict = {"Asian Paints": "ASIANPAINT.NS", "Britannia": "BRITANNIA.NS", "Cipla": "CIPLA.NS", 
               "Eicher Motors": "EICHERMOT.NS", "Nestle India": "NESTLEIND.NS", "Grasim": "GRASIM.NS", 
               "Hero MotoCorp": "HEROMOTOCO.NS", "Hindalco": "HINDALCO.NS", "Hindustan Unilever": "HINDUNILVR.NS", 
               "ITC": "ITC.NS", "Larsen & Toubro": "LT.NS", "Mahindra & Mahindra": "M&M.NS", 
               "Reliance": "RELIANCE.NS", "Tata Consumer Products": "TATACONSUM.NS", 
               "Tata Motors": "TATAMOTORS.NS", "Tata Steel": "TATASTEEL.NS", "Wipro": "WIPRO.NS", 
               "Apollo Hospitals Enterprise": "APOLLOHOSP.NS", "Dr Reddys Laboratories": "DRREDDY.NS", 
               "Titan Company": "TITAN.NS", "State Bank of India": "SBIN.NS", "Shriram Finance": "SHRIRAMFIN.NS", 
               "Bharat Petroleum Corporation": "BPCL.NS", "Kotak Mahindra Bank": "KOTAKBANK.NS", "Infosys": "INFY.NS", 
               "Bajaj Finance": "BAJFINANCE.NS", "Adani Enterprises": "ADANIENT.NS", 
               "Sun Pharmaceuticals": "SUNPHARMA.NS", "JSW Steel": "JSWSTEEL.NS", "HDFC Bank": "HDFCBANK.NS", 
               "Tata Consultancy Services": "TCS.NS", "ICICI Bank": "ICICIBANK.NS", 
               "Power Grid Corporation of India": "POWERGRID.NS", "Maruti Suzuki India": "MARUTI.NS", 
               "IndusInd Bank": "INDUSINDBK.NS", "Axis Bank": "AXISBANK.NS", "HCL Technologies": "HCLTECH.NS", 
               "Oil & Natural Gas Corporation": "ONGC.NS", "NTPC": "NTPC.NS", "Coal India": "COALINDIA.NS", 
               "Bharti Airtel": "BHARTIARTL.NS", "Tech Mahindra": "TECHM.NS", "LTIMindtree": "LTIM.NS", 
               "Divis Laboratories": "DIVISLAB.NS", "Adani Ports & Special Economic Zone": "ADANIPORTS.NS", 
               "HDFC Life Insurance Company": "HDFCLIFE.NS", "SBI Life Insurance Company": "SBILIFE.NS", 
               "UltraTech Cement": "ULTRACEMCO.NS", "Bajaj Auto": "BAJAJ-AUTO.NS", "Bajaj Finserv": "BAJFINANCE.NS"
               }